[project]
name = "your-package-name"
version = "0.0.1"
description = "A brief description of your package"
authors = ["Your Name <your.email@example.com>"]

[project.dependencies]
dependency1 = "^1.0"
dependency2 = "^2.0"

[project.extras]
extra_feature = ["dependency3", "dependency4"]
